name: Build and Test

# Trigger the workflow on push or pull request to your branch
on:
  push:
    branches:
      - your-branch-name
  pull_request:
    branches:
      - your-branch-name

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' # Specify the Python version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run tests
      - name: Run tests
        run: |
          python -m unittest discover -s notes-test/src/test -p '*.py'
