name: Build and Test

on:
  push:
    branches:
      - samaydhirwani
  pull_request:
    branches:
      - samaydhirwani

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you need

      # Step 3: Install dependencies (none in this case, so it's skipped)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add this if you have a requirements.txt
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run tests
      - name: Run tests
        run: |
          python -m unittest discover -s notes-test/src/tests -p '*.py'
